# Generated by Django 3.2.6 on 2021-08-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_video_subtitles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='audios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='index.audio'),
        ),
        migrations.AlterField(
            model_name='content',
            name='texts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='index.text'),
        ),
        migrations.AlterField(
            model_name='content',
            name='videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='index.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitles_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/%Y/%m/%d/'),
        ),
    ]
