# Generated by Django 3.2.6 on 2021-08-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210829_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
