# Generated by Django 3.2.6 on 2021-08-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_audio_bitrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='audios',
        ),
        migrations.RemoveField(
            model_name='content',
            name='texts',
        ),
        migrations.RemoveField(
            model_name='content',
            name='videos',
        ),
        migrations.AddField(
            model_name='content',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.audio'),
        ),
        migrations.AddField(
            model_name='content',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.text'),
        ),
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.video'),
        ),
    ]
