# Generated by Django 3.2.6 on 2021-08-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210829_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video',
        ),
        migrations.AddField(
            model_name='audio',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='index.content'),
        ),
        migrations.AddField(
            model_name='text',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='index.content'),
        ),
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='index.content'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='data_file',
            field=models.FileField(upload_to='static/audio/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='data_file',
            field=models.FileField(upload_to='static/video/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitles_file',
            field=models.FileField(blank=True, null=True, upload_to='static/subtitles/%Y/%m/%d/'),
        ),
    ]
