# Generated by Django 3.2.6 on 2021-08-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210829_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='index.content'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='index.content'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='index.content'),
        ),
    ]
