# Generated by Django 3.2.6 on 2021-08-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20210829_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='content',
        ),
        migrations.RemoveField(
            model_name='text',
            name='content',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.audio'),
        ),
        migrations.AddField(
            model_name='content',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.text'),
        ),
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.video'),
        ),
    ]
